[package]
name = "pom"
version = "0.2.1"
authors = ["Oliver Pieper <pieper@viaregio.de>"]
description = "A simple pomodoro timer written in Rust."
edition = "2018"

[dependencies]
chrono = "0.4.15"
clap = "3.0.0-beta.2"
ctrlc = "3.1.6"
humantime = "2.0.1"
indicatif = "0.15.0"
log = "0.4.11"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
simple-logging = "2.0.2"
winrt-notification = "0.3.0"
